### ISSUE TITLE
jackson-annotation version in BOM

### ISSUE THREAD

**Issue by ranarula** [FasterXML/jackson-bom#15]
Why does the BOM has a different version for `jackson-annotation` than the others. 
e.g.  jackson bom version 2.9.5 refers to `jackson-annotation` version `2.9.0` when version `2.9.5` of the same is available.

I went through #4 but seems the issue is still there for version 2.9.5
Do we wait for version 3.0.0 when the `jackson-annotation` will eventually get  rid of patch info from the versions.

**Comment by andrei-ivanov** [comment]
@cowtowncoder Is this intentional or a real bug?
I've just noticed the same version discrepancy in the app lib.

**Comment by cowtowncoder** [comment]
This is intentional and not version discrepancy.

ALL annotation patch versions are identical. 3.0 will indeed drop the patch version, but until then you can use either 2.9.5 or 2.9.0. BOM specifies 2.9.0 as there is no benefit whatsoever from using later version. But some users use a single version and want to use that.
